### ISSUE TITLE
New random autoteam selection causes crash

### ISSUE THREAD

**Issue by allejo** [BZFlag-Dev/bzflag#20]
The current master branch crashes on occasion when teams are automatically selected.

Server conf:

```
# no -autoteam
-mp 0,16,0,16,0,5
```

Message:

```
Program received signal SIGFPE, Arithmetic exception.
0x00000000004598e8 in teamSelect (t=t@entry=AutomaticTeam, teams=...) at bzfs.cxx:1756
1756	  return teams[rand() % teams.size()].color;
```

Backtrace:

```
(gdb) bt
#0  0x00000000004598e8 in teamSelect (t=t@entry=AutomaticTeam, teams=...) at bzfs.cxx:1756
#1  0x0000000000506b6a in autoTeamSelect (t=AutomaticTeam) at bzfs.cxx:1840
#2  AddPlayer (playerIndex=playerIndex@entry=2, playerData=playerData@entry=0x89c080) at bzfs.cxx:2102
#3  0x000000000045d7ad in doStuffOnPlayer (playerData=...) at bzfs.cxx:5278
#4  main (argc=<optimized out>, argv=<optimized out>) at bzfs.cxx:6727
```

Full backtrace:

```
#0  0x00000000004598e8 in teamSelect (t=t@entry=AutomaticTeam, teams=...) at bzfs.cxx:1756
No locals.
#1  0x0000000000506b6a in autoTeamSelect (t=AutomaticTeam) at bzfs.cxx:1840
        numplayers = <optimized out>
        i = <optimized out>
        teams = {<std::_Vector_base<TeamSize, std::allocator<TeamSize> >> = {_M_impl = {<std::allocator<TeamSize>> = {<__gnu_cxx::new_allocator<TeamSize>> = {<No data fields>}, <No data fields>}, _M_start = 0x939130, _M_finish = 0x939148, _M_end_of_storage = 0x939148}}, <No data fields>}
        maxTeamSize = 1
        unBalanced = <optimized out>
#2  AddPlayer (playerIndex=playerIndex@entry=2, playerData=playerData@entry=0x89c080) at bzfs.cxx:2102
        allowData = {<bz_EventData> = {_vptr.bz_EventData = 0x5977f0 <vtable for bz_AllowPlayerEventData_V1+16>, version = 1, eventType = bz_eAllowPlayer, eventTime = 1280.5844450031493}, playerID = 2, callsign = {data = 0x939360}, ipAddress = {data = 0x9311d0}, reason = {data = 0x930e00}, allow = true}
        result = <optimized out>
        rejectMsg = "\000\000\000\000\000\000\000\000\033", '\000' <repeats 13 times>, " \000\255gL", '\000' <repeats 21 times>, "\060\026\223", '\000' <repeats 13 times>, "\n\301\211\000\000\000\000\000\200\300\211\000\000\000\000\000\260ŉ\000\000\000\000\000>\331\r\367\377\177\000\000\360\333\377\377\377\177\000\000\n\301\211\000\000\000\000\000\210\300\211", '\000' <repeats 12 times>
        playerIP = {s_addr = 131947103}
        info = {addr = {s_addr = 131947103}, cidr = 32 ' ', banEnd = {seconds = 315360000000, static currentTime = <same as static member of an already seen type>, static tickTime = <same as static member of an already seen type>, static sunExplodeTime = <same as static member of an already seen type>, 
            static sunGenesisTime = <same as static member of an already seen type>, static nullTime = <same as static member of an already seen type>, static startTime = <same as static member of an already seen type>}, bannedBy = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7de338 <std::string::_Rep::_S_empty_rep_storage@@GLIBCXX_3.4+24> ""}}, reason = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7de338 <std::string::_Rep::_S_empty_rep_storage@@GLIBCXX_3.4+24> ""}}, fromMaster = false}
        numplayersobs = <optimized out>
        teamIndex = <optimized out>
        message = "\000\000\000\000\000\000\000\000\334\066H\000\000\000\000\000@\337\377\377\377\177\000\000\200\300\211\000\000\000\000\000\300\337\377\377\377\177\000\000`g\321\366\377\177\000\000\070\343}\000\000\000\000\000\v\000\000\000\000\000\000\000`\376\222\000\000\000\000\000\003\000\000\000\000\000\000\000\067\000\000\000\000\000\000\000\340\336\377\377\377\177\000\000\000\000\000\000\000\000\000\000\341\032N\000\000\000\000\000\000\300\211\000\000\000\000\000\310\350\230\000\000\000\000"
        resultEnter = <optimized out>
        playerIsAntiBanned = <optimized out>
        t = <optimized out>
        autoTeamData = {<bz_EventData> = {_vptr.bz_EventData = 0x8, version = 9745680, eventType = bz_eNullEvent, eventTime = 0}, playerID = -154048672, callsign = {data = 0x34}, team = eRogueTeam, handled = false}
        numplayers = <optimized out>
        buf = <optimized out>
        mottoEvent = {<bz_GetPlayerMottoData_V1> = {<bz_EventData> = {_vptr.bz_EventData = 0x140e0, version = -154048672, eventType = 32767, eventTime = 5.1199825252270043e-317}, motto = {data = 0x13a00}}, record = 0x0}
        lines = 0x0
        rejectCode = 0
        idInfo = {idpat = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7de338 <std::string::_Rep::_S_empty_rep_storage@@GLIBCXX_3.4+24> ""}}, banEnd = {seconds = 315360000000, 
            static currentTime = <same as static member of an already seen type>, static tickTime = <same as static member of an already seen type>, static sunExplodeTime = <same as static member of an already seen type>, static sunGenesisTime = <same as static member of an already seen type>, 
            static nullTime = <same as static member of an already seen type>, static startTime = <same as static member of an already seen type>}, bannedBy = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x7de338 <std::string::_Rep::_S_empty_rep_storage@@GLIBCXX_3.4+24> ""}}, reason = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x7de338 <std::string::_Rep::_S_empty_rep_storage@@GLIBCXX_3.4+24> ""}}, fromMaster = false}
        joinEventData = {<bz_EventData> = {_vptr.bz_EventData = 0x4, version = 0, eventType = bz_eNullEvent, eventTime = 6.953355807370138e-310}, playerID = -157440080, record = 0x98ac20, reason = {data = 0x34}}
#3  0x000000000045d7ad in doStuffOnPlayer (playerData=...) at bzfs.cxx:5278
        eventData = {<bz_EventData> = {_vptr.bz_EventData = 0x597e30 <vtable for bz_ServerAddPlayerData_V1+16>, version = 1, eventType = bz_eServerAddPlayer, eventTime = 1280.5844420031492}, player = 0x89c5b0, allow = true}
        warn = false
        kick = false
        nextPingSeqno = <optimized out>
#4  main (argc=<optimized out>, argv=<optimized out>) at bzfs.cxx:6727
        p = 2
        dropTime = <optimized out>
        timeout = {tv_sec = 0, tv_usec = 0}
        peerItr = <optimized out>
        resetGame = <optimized out>
        read_set = {fds_bits = {0 <repeats 16 times>}}
        write_set = {fds_bits = {0 <repeats 16 times>}}
        tm = {seconds = 1280.5844410031491, static currentTime = <same as static member of an already seen type>, static tickTime = <same as static member of an already seen type>, static sunExplodeTime = <same as static member of an already seen type>, 
          static sunGenesisTime = <same as static member of an already seen type>, static nullTime = <same as static member of an already seen type>, static startTime = <same as static member of an already seen type>}
        pluginMaxWait = <optimized out>
        toKill = {<std::_Vector_base<int, std::allocator<int> >> = {_M_impl = {<std::allocator<int>> = {<__gnu_cxx::new_allocator<int>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}
        waitTime = 0
        itr = <optimized out>
        cURLmaxFile = <optimized out>
        adLines = 0x0
        tickData = {<bz_EventData> = {_vptr.bz_EventData = 0x584c30 <vtable for bz_EventData+16>, version = 1, eventType = bz_eTickEvent, eventTime = 1280.5843030031476}, <No data fields>}
        nfound = 0
        nextSuperFlagInsertion = {seconds = 0.62012499999999993, static currentTime = <same as static member of an already seen type>, static tickTime = <same as static member of an already seen type>, static sunExplodeTime = <same as static member of an already seen type>, 
          static sunGenesisTime = <same as static member of an already seen type>, static nullTime = <same as static member of an already seen type>, static startTime = <same as static member of an already seen type>}
        flagExp = 0.0693147182
        i = <optimized out>
```
/cc @macsforme

**Comment by macsforme** [comment]
Hopefully fixed in 79f046f (won't get into master until the next merge). Please advise if so, since I wasn't able to reproduce it during my testing.

**Comment by allejo** [comment]
Will test later tonight to see if it still segfaults or if I can replicate the issue

**Comment by allejo** [comment]
Haven't seen any crashes after recent commits, though I was never sure how to replicate this the begin with. I'll close the issue for now unless it segfaults again
